<?php

declare(strict_types=1);

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Vite;
use Illuminate\View\ViewException;
use Labidi\Recaptcha\Exceptions\InvalidConfigurationException;

function renderBlade(string $template): string
{
    return Blade::render($template);
}

/**
 * Render a template and return the configuration error it raised. Blade wraps
 * exceptions thrown while rendering in a ViewException.
 */
function renderingError(string $template): InvalidConfigurationException
{
    try {
        renderBlade($template);
    } catch (ViewException $e) {
        expect($e->getPrevious())->toBeInstanceOf(InvalidConfigurationException::class);

        return $e->getPrevious();
    }

    throw new RuntimeException('Expected rendering to fail.');
}

describe('script', function () {
    it('loads api.js with the v3 site key and the shared onload callback', function () {
        $html = renderBlade('<x-recaptcha::script />');

        expect($html)
            ->toContain('src="https://www.google.com/recaptcha/api.js?render=test-site-key&amp;onload=__labidiRecaptchaOnload"')
            ->toContain(' async')
            ->toContain(' defer')
            ->toContain('window.__labidiRecaptcha=window.__labidiRecaptcha||');
    });

    it('uses explicit rendering for v2', function () {
        config(['recaptcha.version' => 'v2-checkbox']);

        expect(renderBlade('<x-recaptcha::script />'))->toContain('api.js?render=explicit&amp;onload=');
    });

    it('renders the same markup through the directive', function () {
        expect(renderBlade('@recaptchaScript'))->toBe(renderBlade('<x-recaptcha::script />'));
    });

    it('honours per-use attributes', function () {
        $html = renderBlade('<x-recaptcha::script :async="false" :defer="false" nonce="abc123" />');

        expect($html)
            ->not->toContain(' async')
            ->not->toContain(' defer')
            ->toContain('nonce="abc123"');
    });

    it('uses the CSP nonce generated by Vite', function () {
        Vite::useCspNonce('vite-nonce');

        expect(renderBlade('@recaptchaScript'))->toContain('nonce="vite-nonce"');
    });

    it('uses the configured script host and language', function () {
        config([
            'recaptcha.script_url' => 'https://www.recaptcha.net/recaptcha/api.js',
            'recaptcha.attributes.language' => 'ar',
        ]);

        expect(renderBlade('@recaptchaScript'))
            ->toContain('https://www.recaptcha.net/recaptcha/api.js?render=test-site-key')
            ->toContain('hl=ar');
    });
});

describe('field', function () {
    it('renders a v3 hidden input that executes the given action on submit', function () {
        $html = renderBlade('<x-recaptcha::field action="login" id="captcha" />');

        expect($html)
            ->toContain('<input type="hidden" id="captcha" name="g-recaptcha-response"')
            ->toContain("grecaptcha.execute('test-site-key', { action: 'login' })")
            ->toContain("form.addEventListener('submit'");
    });

    it('defaults the v3 action to "submit"', function () {
        expect(renderBlade('<x-recaptcha::field />'))->toContain("{ action: 'submit' }");
    });

    it('uses the configured v3 field name', function () {
        config(['recaptcha.field_name' => 'captcha_token']);

        expect(renderBlade('@recaptchaField'))->toContain('name="captcha_token"');
    });

    it('renders through the directive with arguments', function () {
        $html = renderBlade("@recaptchaField('register')");

        expect($html)->toContain("{ action: 'register' }");
    });

    it('renders a v2 checkbox widget with configured and overridden options', function () {
        config(['recaptcha.version' => 'v2-checkbox']);

        $html = renderBlade('<x-recaptcha::field theme="dark" id="box" class="mt-4" />');

        expect($html)
            ->toContain('<div id="box" class="recaptcha-widget mt-4"></div>')
            ->toContain('grecaptcha.render(el, params)')
            ->toContain('test-site-key')
            ->toContain('dark')
            ->not->toContain('invisible')
            ->not->toContain('<input type="hidden"');
    });

    it('renders the v2 invisible widget bound to its form', function () {
        config(['recaptcha.version' => 'v2-invisible', 'recaptcha.attributes.badge' => 'bottomleft']);

        $html = renderBlade('@recaptchaField');

        expect($html)
            ->toContain('invisible')
            ->toContain('bottomleft')
            ->toContain('grecaptcha.execute(widgetId)')
            ->toContain("el.closest('form')");
    });

    it('generates unique ids so several forms can share a page', function () {
        $html = renderBlade('@recaptchaField @recaptchaField');

        preg_match_all('/id="(recaptcha-[a-z0-9]+)"/', $html, $matches);

        expect($matches[1])->toHaveCount(2)
            ->and($matches[1][0])->not->toBe($matches[1][1]);
    });
});

describe('widget', function () {
    it('renders the v2 widget', function () {
        config(['recaptcha.version' => 'v2-checkbox']);

        expect(renderBlade('<x-recaptcha::widget />'))->toContain('grecaptcha.render(el, params)')
            ->and(renderBlade('@recaptchaWidget'))->toContain('grecaptcha.render(el, params)');
    });

    it('accepts named arguments in the directive', function () {
        config(['recaptcha.version' => 'v2-checkbox']);

        expect(renderBlade("@recaptchaWidget(theme: 'dark', id: 'named')"))
            ->toContain('<div id="named"')
            ->toContain('dark');
    });

    it('refuses to render a v2 widget against a v3 key', function () {
        expect(renderingError('<x-recaptcha::widget />')->getMessage())->toContain('<x-recaptcha::field>');
    });
});

describe('when disabled or unconfigured', function () {
    it('renders nothing when disabled', function (string $template) {
        config(['recaptcha.enabled' => false]);

        expect(trim(renderBlade($template)))->toBe('');
    })->with(['<x-recaptcha::script />', '<x-recaptcha::field />', '@recaptchaScript', '@recaptchaField']);

    it('throws a clear error when the site key is missing', function () {
        config(['recaptcha.site_key' => null]);

        expect(renderingError('@recaptchaScript')->getMessage())->toContain('RECAPTCHA_SITE_KEY');
    });

    it('renders nothing without a site key in a skipped environment', function () {
        config(['recaptcha.site_key' => null, 'recaptcha.skip_environments' => ['testing']]);

        expect(trim(renderBlade('@recaptchaScript @recaptchaField')))->toBe('');
    });
});
